Bolt Payment View Fixes
nebulab/solidus_bolt pull request #62
Opened 2022-05-12 06:00 UTC by Naokimi

This PR includes a series of minor fixes related to Bolt payment views:
- Display Bolt payment option in admin panel
- Add API payment view for Bolt (fixes https://github.com/nebulab/solidus_bolt/issues/58)
- Hide extra button on Bolt iframe display

2022-05-12 10:33 UTC, DanielePalombo requested changes
I've got an error trying to submit the payment from admin.
<img width="1534" alt="Screenshot 2022-05-12 at 12 15 34" src="https://user-images.githubusercontent.com/387690/168050349-fe4f062a-f138-42fa-8d9d-36ce847fef15.png">

I have got another error visiting the payment page from admin.

<img width="1359" alt="Screenshot 2022-05-12 at 12 19 56" src="https://user-images.githubusercontent.com/387690/168050742-b59234c6-4f89-4edb-8890-035cf874b2b4.png">

The error is related to solidus and I added a [commit](https://github.com/nebulab/solidus_bolt/commit/a1275e855df73afbc3a096b6447b005ce1bb08c8) to help you to fix it.

2022-05-13 04:17 UTC, piyushswain commented
Caught an error in console while testing this PR
```
solidus_bolt.source.js:63 Uncaught (in promise) ReferenceError: Bolt is not defined
```

I think the error is from these lines
```js
document.addEventListener("DOMContentLoaded", async function () {
  const boltContainer = document.getElementById("bolt-container");
  const boltEmbedded = Bolt(boltContainer.dataset.publishableKey);
  const accountCheckbox = boltEmbedded.create("account_checkbox");
```

2022-05-13 04:18 UTC, Naokimi commented
I'm aware of that one but afaik it doesn't break anything

2022-05-13 07:28 UTC, DanielePalombo commented
> I'm aware of that one but afaik it doesn't break anything

Do you understand what generates the error?

2022-05-13 08:55 UTC, Naokimi commented
@DanielePalombo yes, pushed the fix

2022-05-13 10:47 UTC, DanielePalombo approved these changes

2022-05-13 10:48 UTC, merged